### ISSUE TITLE
Patch cborg-0.2.0.0

### ISSUE THREAD

**Issue by jneira** [typelead/eta-hackage#111]
[cborg](http://hackage.haskell.org/package/cborg) "provides an efficient implementation of the Concise Binary Object Representation (CBOR), as specified by RFC 7049." and is used in the master version of dhall-haskell to serialize dhall

**Comment by rahulmutt** [comment]
Patch is ready. Unfortunately there were no tests in the package for me to verify whether it was correct (but I'm pretty sure it should mostly be correct) so let me know if you face any issues.
