### ISSUE TITLE
Cryptonite

### ISSUE THREAD

**Issue by noughtmare** [typelead/eta-hackage#16]
Is it possible to support cryptonite?

**Comment by rahulmutt** [comment]
Yes of course., but `cryptonite` is a library a huge chunk of C code. It'll take some time to port. 

For anyone interesting in porting, the following Java classes can useful:
- https://docs.oracle.com/javase/7/docs/api/javax/crypto/Cipher.html
- https://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#Cipher

**Comment by joaomilho** [comment]
+1

**Comment by AlexeyRaga** [comment]
+1, it looks that it is required for `servant-client`

**Comment by rahulmutt** [comment]
`cryptonite` is now available on Eta v0.7. Most of the hash functions have been implemented. Some of the others may be need implementation, please file issues accordingly.
