### ISSUE TITLE
filepath

### ISSUE THREAD

**Issue by joaomilho** [typelead/eta-hackage#22]
I see filepath was updated just a couple of hours ago, but when I try to install it I get:

```
Preprocessing library filepath-1.4.1.2...
[1 of 3] Compiling System.FilePath.Windows ( System/FilePath/Windows.hs, dist/build/System/FilePath/Windows.jar )

System/FilePath/Internal.hs:110:1:
    System.Environment: Can't be safely imported!
    The module itself isn't safe.
Failed to install filepath-1.4.1.2
```

Maybe I need to understand a little better how eta-hackage works. Are all packages got directly from master once updated or there's some delay (like publishing it somewhere)?

**Comment by rahulmutt** [comment]
You need to run `epm update` and try again.

**Comment by joaomilho** [comment]
works! thanks
