### ISSUE TITLE
instructions on adding packages are unclear

### ISSUE THREAD

**Issue by joaomilho** [typelead/eta-hackage#23]
If one follows...

```
Patching

Download the somepackage-0.1.2.3.tar.gz tarball from Hackage.

Initialize a git repository and make an initial commit.

$ git init
$ git add .
$ git commit -m "First"
Build the package.

$ epm build
```

... the result can only be ...

```
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
epm: No cabal file found.
Please create a package description file <pkgname>.cabal
```

I suppose the instructions need to explain about how this new repo needs to be properly started, and to avoid confusion it should be clear that one needs to move the tar into that same folder.

**Comment by rahulmutt** [comment]
Those instructions are several months old and no one has been asking questions so it's been left as is :) Since you've asked, I'll update the instructions.

**Comment by rahulmutt** [comment]
I've updated the instructions. Let me know if that helped or if there's still something that's unclear.

**Comment by joaomilho** [comment]
Thanks!

**Comment by rahulmutt** [comment]
This seems to be resolved, closing. If you have anymore questions, you can open a new issue.
