### ISSUE TITLE
Support for "extra" package

### ISSUE THREAD

**Issue by sertel** [typelead/eta-hackage#30]
Hi,

I would like to use the extra package but it is not yet supported.
After a small chat on Gitter, it seems that the following would have to be done:

- patch the package in order to remove the dependency on the unix package
- remove/handle the FFI call

Thanks,
Sebastian.

**Comment by rahulmutt** [comment]
Which modules in this package do you need right now?

**Comment by sertel** [comment]
I need the module `Control.Monad.Extra`.

**Comment by Abhiroop** [comment]
https://github.com/typelead/eta-hackage/pull/31 patches extra to atleast facilitate the usage of `Control.Monad.Extra`

**Comment by rahulmutt** [comment]
Closing as this is resolved.
