### ISSUE TITLE
Patch process-1.6.2.0

### ISSUE THREAD

**Issue by phanimahesh** [typelead/eta-hackage#66]
Here's what happens today:

```
Configuring process-1.6.2.0...
Preprocessing library for process-1.6.2.0..
Building library for process-1.6.2.0..
[1 of 5] Compiling System.Process.Common ( System/Process/Common.hs, dist/dist-sandbox-f6755099/build/System/Process/Common.jar )

System/Process/Common.hs:206:24: Not in scope: ‘FD.fdPath’
```

There's no FD.fdPath in the source. https://hackage.haskell.org/package/process-1.6.2.0/src/System/Process/Common.hs

I'm probably missing something obvious, any hints?

**Comment by rahulmutt** [comment]
The patch only works on the `master` version of Eta. You can try installing the latest version or wait for the next binary release which should happen within a couple of weeks.

**Comment by rahulmutt** [comment]
Eta v0.7 is out which should allow the above to work, you can run `etlas select latest` to get it.
