### ISSUE TITLE
directory-1.3.1.0 fix createDirectoryIfMissing

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta-hackage#79]
@jniera, unfortunately I'm getting the following error from your patch file:

```
Found patch in eta-hackage for directory-1.3.1.0
etlas: '/usr/bin/git' exited with an error:
fatal: unrecognized input
```

I've temporarily reverted your changes so that builds don't break. If at all possible can you revert your git version and see if that helps?

**Comment by jneira** [comment]
Hi, sorry for the additional work. I am trying to make the patch in dos console (instead powershell, see https://stackoverflow.com/questions/13675782/git-shell-in-windows-patchs-default-character-encoding-is-ucs-2-little-endian) and i get to avoid the `fatal: unrecognized input`. 
However i am testing the patch locally and i get some rejected hunks and a bad version.

**Comment by jneira** [comment]
Ok, after reset the package to the initial state the patch created in dos console is correctly applied and the package builds so the problem was using `git format-patch` in powershell
I'll go ahead and request a new pr with the well-formed patch

**Comment by rahulmutt** [comment]
@jneira Can this be closed now?

**Comment by jneira** [comment]
closing!
