### ISSUE TITLE
[Patch Request] MissingH-1.4.0.1

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta-hackage#93]
The `unix` dependency needs to be commented out and all the missing functions should be replaced with a Java standard library shim (if possible). If not possible, the definition of the function can be replaced with an `error "[message-here]"` expression for now.

**Comment by Jyothsnasrinivas** [comment]
@scameronde I just patched `MissingH-1.4.0.1`. You should be able to use it now!
